---
- key: pg.db.discovery
  description: >
    Returns a JSON array of all known PostgreSQL databases which are available
    for connection by the authenticated user
  type: Discovery
  source: >
    SELECT
      d.oid AS oid,
      d.datname AS database,
      pg_catalog.pg_encoding_to_char(d.encoding) AS encoding,
      d.datcollate AS lc_collate,
      d.datctype AS lc_ctype,
      pg_catalog.pg_get_userbyid(d.datdba) AS owner,
      t.spcname AS tablespace,
      pg_catalog.shobj_description(d.oid, 'pg_database') AS description
    FROM pg_catalog.pg_database d
        JOIN pg_catalog.pg_tablespace t ON d.dattablespace = t.oid
    WHERE
        d.datallowconn = 't'
        AND d.datistemplate = 'n'
    ORDER BY 1;
  macros:
    - macro: "{#OID}"
      description: Database unique identifier
    - macro: "{#DATABASE}"
      description: >
        Database name (this macro should be used as the second parameter in all
        created item prototypes for this discovery rule)
    - macro: "{#ENCODING}"
      description: Character encoding for this database
    - macro: "{#LC_COLLATE}"
      description: LC_COLLATE for this database
    - macro: "{#LC_CTYPE}"
      description: LC_CTYPE for this database
    - macro: "{#OWNER}"
      description: Owner of the database, usually the user who created it
    - macro: "{#TABLESPACE}"
      description: The default tablespace for the database
    - macro: "{#DESCRIPTION}"
      description: Database description

- key: pg.db.size
  description: >
    Returns the size in bytes of a PostgreSQL database. If no database is
    specifed, the sum size of all databases is returned.
  type: Numeric (unsigned)
  units: Bytes
  parameters:
    - parameter: database
      description: database to return size for. May be different to the connected database.
      default: sum of all databases
  source: >
    SELECT 
      pg_catalog.pg_database_size(d.datname)
    FROM pg_catalog.pg_database d
    WHERE d.datname = $1
  example: pg.db.size[,,my_db]

- key: pg.db.numbackends
  description: >
    Returns the number of backends currently connected to this database. This
    is the only column in this view that description: Returns a value
    reflecting current state; all other columns return the accumulated values
    since the last reset.
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.xact_commit
  description: Returns the number of transactions in this database that have been committed
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.xact_rollback
  description: Returns the number of transactions in this database that have been rolled back
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.blks_read
  description: Returns the number of disk blocks read in this database
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.blks_hit
  description: >
    Returns the number of times disk blocks were found already in the buffer
    cache, so that a read was not necessary (this only includes hits in the
    PostgreSQL buffer cache, not the operating system's file system cache)
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.blks_ratio
  description: >
    Returns the percentage of in-memory cache hits to disk reads as a fraction
    of 1.

    A high value (close to 1) indicates most reads are served from cache,
    while a low value (close to 0) indicates most reads are served from slower
    disk media.

  type: Numeric (float)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: average for all database

- key: pg.db.tup_returned
  description: Returns the number of rows returned by queries in this database
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.tup_fetched
  description: Returns the number of rows fetched by queries in this database
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.tup_inserted
  description: Returns the number of rows inserted by queries in this database
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.tup_updated
  description: Returns the number of rows updated by queries in this database
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.tup_deleted
  description: Returns the number of rows deleted by queries in this database
  type: Numeric (unsigned)
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.conflicts
  description: >
    Returns the number of queries canceled due to conflicts with recovery in
    this database. (Conflicts occur only on standby servers; see
    pg_stat_database_conflicts for details.)
  type: Numeric (unsigned)
  require: 9.1
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.temp_files
  description: >
    Returns the number of temporary files created by queries in this database.
    All temporary files are counted, regardless of why the temporary file was
    created (e.g., sorting or hashing), and regardless of the log_temp_files
    setting.
  type: Numeric (unsigned)
  require: 9.2
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.temp_bytes
  description: >
    Returns the total amount of data written to temporary files by queries in
    this database. All temporary files are counted, regardless of why the
    temporary file was created, and regardless of the log_temp_files setting.
  type: Numeric (unsigned)
  units: Bytes
  require: 9.2
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.deadlocks
  description: Returns the number of deadlocks detected in this database
  type: Numeric (unsigned)
  require: 9.2
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.blk_read_time
  description: >
    Returns the time spent reading data file blocks by backends in this
    database, in milliseconds
  type: Numeric (unsigned)
  units: Milliseconds
  require: 9.2
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.blk_write_time
  description: >
    Returns the time spent writing data file blocks by backends in this
    database, in milliseconds
  type: Numeric (unsigned)
  units: Milliseconds
  require: 9.2
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
      default: sum for all database

- key: pg.db.stats_reset
  description: Returns the time at which these statistics were last reset
  type: Text
  require: 9.1
  parameters:
    - parameter: database
      description: >
        return statistics for this database (may differ from the connected
        database)
